# Generated by Django 4.1 on 2022-09-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Стать'),
        ),
    ]
