# Generated by Django 4.1 on 2022-09-02 14:58

from django.db import migrations, models
import djangogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0006_alter_post_tags_alter_tag_title_alter_tag_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=djangogram.models.Image.get_uniq_name, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=djangogram.models.Profile.get_uniq_name, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag'),
        ),
    ]
