# Generated by Django 4.1 on 2022-09-03 06:50

from django.db import migrations, models
import djangogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0007_alter_image_image_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=djangogram.models.Profile.get_uniq_name, verbose_name='Фото'),
        ),
    ]
