# Generated by Django 4.1 on 2022-09-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0008_alter_profile_bio_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
    ]
